### PR TITLE
fix neovim freeze when closing a type_identifier

### LINKED ISSUE #222: React Typescript - Freezes Neovim after opening a generic of a function
Hey,
I'm currently facing a very big issue with autotag.
Whenever I wish to use a generic on a function I type the opening angled bracket (<) but as soon as I do that
the entire terminal freezes.

I narrowed it down to this extension when I tried removing it and attempting it again. If I try to type generic type parameters for a function it completely freezes until I close the tmux window and reopen it.

### PR DESCRIPTION
**Pull request by pnwatin**
close #222 

Avoid a potential infinite loop when checking if `is_in_template_tag()` when closing a `type_indentifier` ts node.

### CODE REVIEW

File: lua/nvim-ts-autotag/internal.lua [hunk 1]
```diff
@@ -44,7 +44,12 @@ local function is_in_template_tag()
     local has_template_string = false
 
     local current_node = cursor_node
+    local visited_nodes = {}
     while not (has_element and has_template_string) and current_node do
+        if visited_nodes[node_id] then
```
Comment (PriceHiller) [inline lua/nvim-ts-autotag/internal.lua:49]: Probably forgot to get the current node id 😄 
```suggestion
        local node_id = current_node:id()
        if visited_nodes[node_id] then
```

Comment (pnwatin) [reply lua/nvim-ts-autotag/internal.lua:50]: good catch ! 😅
